defaultContentLanguage = "zh-cn"
baseURL = "/"
locale = "zh-CN"
title = "老子爱读书"

disableKinds = []

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
taxonomy = ["HTML"]
term = ["HTML"]

[sitemap]
changeFreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

enableRobotsTXT = true
