defaultContentLanguage = "zh-cn"
baseURL = "https://laoziaidushu.com/"
locale = "zh-CN"
title = "老子爱读书"

disableKinds = []
enableRobotsTXT = true
enableGitInfo = true

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
taxonomy = ["HTML"]
term = ["HTML"]

[sitemap]
changeFreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[related]
includeNewer = true
threshold = 10
toLower = true

[[related.indices]]
name = "categories"
weight = 100

[[related.indices]]
name = "tags"
weight = 70
